from pathlib import Path
import subprocess

from rdkit import Chem
from rdkit.Chem import AllChem


def write_xyz(mol, filename):
    conf = mol.GetConformer()
    atoms = mol.GetAtoms()

    with open(filename, "w", encoding="utf-8") as f:
        f.write(f"{len(atoms)}\n")
        f.write("Generated by RDKit\n")

        for atom in atoms:
            pos = conf.GetAtomPosition(atom.GetIdx())
            f.write(
                f"{atom.GetSymbol():<2} "
                f"{pos.x:>15.8f} "
                f"{pos.y:>15.8f} "
                f"{pos.z:>15.8f}\n"
            )


def write_gaussian_input(
    mol,
    filename,
    name,
    cosmo_path,
    chk_path,
    charge=0,
    multiplicity=1,
    method="B3LYP",
    basis="6-31G(d)",
    mem="2GB",
    nproc=4,
):
    conf = mol.GetConformer()

    with open(filename, "w", encoding="utf-8") as f:
        f.write(f"%chk={chk_path}\n")
        f.write(f"%nprocshared={nproc}\n")
        f.write(f"%mem={mem}\n")
        f.write(f"# {method}/{basis} Opt Freq scrf=cosmors\n\n")
        f.write("Title Card Required\n\n")
        f.write(f"{charge} {multiplicity}\n")

        for atom in mol.GetAtoms():
            pos = conf.GetAtomPosition(atom.GetIdx())
            f.write(
                f" {atom.GetSymbol():<2}"
                f"{pos.x:>18.8f}"
                f"{pos.y:>15.8f}"
                f"{pos.z:>15.8f}\n"
            )

        f.write("\n")
        f.write(f" {cosmo_path}\n")
        f.write("\n")

def run_gaussian(gjf_path, log_path, gaussian_cmd="g16"):
    with open(log_path, "w", encoding="utf-8") as fout:
        subprocess.run(
            [gaussian_cmd, str(gjf_path)],
            stdout=fout,
            stderr=subprocess.STDOUT,
            check=True,
        )


def main():
    smiles = input("请输入SMILES：").strip()
    name = input("请输入分子名称：").strip()
    method = input("请输入计算方法（默认 B3LYP）：").strip() or "B3LYP"
    basis = input("请输入基组（默认 6-31G(d)）：").strip() or "6-31G(d)"
    mem = input("请输入内存（默认 2GB）：").strip() or "2GB"
    nproc_text = input("请输入核数（默认 4）：").strip()
    nproc = int(nproc_text) if nproc_text else 4
    charge_text = input("请输入电荷（默认 0）：").strip()
    charge = int(charge_text) if charge_text else 0

    mult_text = input("请输入多重度（默认 1）：").strip()
    multiplicity = int(mult_text) if mult_text else 1

    if not smiles:
        print("SMILES 不能为空")
        return

    if not name:
        print("分子名称不能为空")
        return

    mol = Chem.MolFromSmiles(smiles)

    if mol is None:
        print("SMILES 无效，无法解析")
        return

    print("SMILES 解析成功！")

    # 补氢
    mol = Chem.AddHs(mol)

    # 生成3D结构
    params = AllChem.ETKDGv3()
    params.randomSeed = 42
    result = AllChem.EmbedMolecule(mol, params)

    if result != 0:
        print("3D结构生成失败")
        return

    # 力场优化
    try:
        uff_status = AllChem.UFFOptimizeMolecule(mol, maxIters=2000)
        if uff_status != 0:
            mmff_props = AllChem.MMFFGetMoleculeProperties(mol)
            if mmff_props is not None:
                AllChem.MMFFOptimizeMolecule(mol, mmff_props, maxIters=2000)
    except Exception:
        mmff_props = AllChem.MMFFGetMoleculeProperties(mol)
        if mmff_props is not None:
            AllChem.MMFFOptimizeMolecule(mol, mmff_props, maxIters=2000)

    print("3D结构生成成功！")

    # 项目根目录
    script_path = Path(__file__).resolve()
    project_root = script_path.parent.parent

    tmp_dir = project_root / "tmp"
    gaussian_dir = project_root / "gaussian"
    output_dir = project_root / "output"

    tmp_dir.mkdir(parents=True, exist_ok=True)
    gaussian_dir.mkdir(parents=True, exist_ok=True)
    output_dir.mkdir(parents=True, exist_ok=True)

    xyz_path = tmp_dir / f"{name}.xyz"
    gjf_path = gaussian_dir / f"{name}.gjf"
    log_path = gaussian_dir / f"{name}.log"

    write_xyz(mol, xyz_path)
    print(f"xyz 文件已生成：{xyz_path}")

    chk_path = project_root / "gaussian" / f"{name}.chk"
    cosmo_path = output_dir / f"{name}.cosmo"
    write_gaussian_input(
        mol,
        gjf_path,
        name,
        cosmo_path,
        chk_path,
        charge=charge,
        multiplicity=multiplicity,
        method=method,
        basis=basis,
        mem=mem,
        nproc=nproc,
    )
    print(f"Gaussian 输入文件已生成：{gjf_path}")

    run_now = input("是否立即运行 Gaussian？(y/n)：").strip().lower()
    if run_now == "y":
        try:
            run_gaussian(gjf_path, log_path, gaussian_cmd="g16")
            print(f"Gaussian 输出文件已生成：{log_path}")
        except FileNotFoundError:
            print("未找到 Gaussian 命令 g16，请先确认 Gaussian 已安装并加入 PATH")
        except subprocess.CalledProcessError:
            print("Gaussian 运行失败，请检查 gjf 文件和 Gaussian 环境")
    else:
        print("已跳过 Gaussian 运行。")


if __name__ == "__main__":
    main()